spring:
  application:
    name: demo
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
    driver-class-name: org.h2.Driver
  mybatis:
    mapper-locations: classpath*:application/**/repository/**/*.xml
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

