spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: myuser
    password: mypass
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis:
    mapper-locations: classpath*:application/**/repository/**/*.xml
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

